### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by 41hulk** [JuanLPalacios/todo-list#7]
### Suggestions
 - [x] Keyword modification to increase code redability

**Comment by Kakalanp** [comment]
## Great job @JuanLPalacios! 🎉 

Your list looks great and the _“special effects”_ you gave it are really original and appealing! ✨ 

🧐 Although,


### There are a few issues I'd like to mention to you 🔍:

- The first one being the maximum length of your list: 
![image](https://user-images.githubusercontent.com/78335447/155154190-25323ad0-2a6c-437d-8f1b-eb7f87aad690.png)
😲 There are a lot of items in that screenshot, as you can see, but it shows that after too many elements added, the list breaks.

-----

- The second issue is length-related too: 
![image](https://user-images.githubusercontent.com/78335447/155157082-d25fbb1e-fe69-4b24-9c83-ceff4f0efd4e.png)
🙀 As you can see, the same thing happens horizontally, with a task name that is too long, the text will escape its container and continue on outside the screen.



> A quick solution could be to add an `overflow` property to the container of the items and a `max-width` and `max-height`, that way the items will stay inside and stop pushing everything 😎.

### Good luck implementing the changes!🍀 And, once again, loving your project! 😍
